_target_: {{project_name}}.lightning_modules.DummyModule

network:
  _target_: {{project_name}}.networks.DummyNetwork
  input_size: 10
  output_size: 1

loss_fn:
  _target_: {{project_name}}.losses.MSELoss

defaults:
  - /optimizer: adamw
  - /lr_scheduler: constant
